$ErrorActionPreference = 'Stop'
$env:GRADLE_USER_HOME = 'D:\Demo\Yfuse\.gradle-tmp'
$env:GRADLE_RO_DEP_CACHE = 'C:\Users\app-inkbird\.gradle\caches'
$env:JAVA_HOME = 'C:\Users\app-inkbird\.jdks\ms-21.0.9'
$env:ANDROID_HOME = 'D:\AndroidSDK'
$env:ANDROID_SDK_ROOT = 'D:\AndroidSDK'
$env:JAVA_TOOL_OPTIONS = '-Djdk.net.unixdomain.tmpdir=D:/Demo/Yfuse/gradle.properties'
$gradle = 'D:\Demo\Yfuse\.gradle-tmp\wrapper\dists\gradle-9.5.0-bin\bvnork1r7n8i6kp5cnkibsc9q\gradle-9.5.0\bin\gradle.bat'
$env:PYTHONUTF8 = '1'
& 'C:\Users\app-inkbird\.cache\codex-runtimes\codex-primary-runtime\dependencies\python\python.exe' scripts/android_performance.py --serial RF8M223V4MD --sdk D:/AndroidSDK --runtime-profile full --mode benchmark --output audit/project-implementation-20260910/performance-expanded --gradle-arg=--offline --gradle-arg=--max-workers=1 --gradle-arg=-Porg.gradle.java.installations.paths=C:/Users/app-inkbird/.jdks/corretto-17.0.15,C:/Users/app-inkbird/.jdks/ms-21.0.9 --gradle-arg=-PyfuseIncludeMdk=true '--gradle-arg=-Dorg.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8'
