{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource-okhttp",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.9.0.aar",
          "url": "media3-datasource-okhttp-1.9.0.aar",
          "size": 9781,
          "sha512": "cbb8ebad9e8e6f51cfa7137254f52b398ffabb7cf1cbe9032d56d0a4315de70c1e71d338aa935ec93de1bf654b3646864b5474554b7e64f7fb9c7226b4805351",
          "sha256": "894e02ce6fb0c22b56f96cc2f48b746089f953ae56aa306a535e0edbf6eaa202",
          "sha1": "233268ccebd769d37019e987405f8faccc3d389c",
          "md5": "f259f9b6aaf4e78cabc4c06e680551da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.9.0.aar",
          "url": "media3-datasource-okhttp-1.9.0.aar",
          "size": 9781,
          "sha512": "cbb8ebad9e8e6f51cfa7137254f52b398ffabb7cf1cbe9032d56d0a4315de70c1e71d338aa935ec93de1bf654b3646864b5474554b7e64f7fb9c7226b4805351",
          "sha256": "894e02ce6fb0c22b56f96cc2f48b746089f953ae56aa306a535e0edbf6eaa202",
          "sha1": "233268ccebd769d37019e987405f8faccc3d389c",
          "md5": "f259f9b6aaf4e78cabc4c06e680551da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-okhttp-1.9.0-sources.jar",
          "url": "media3-datasource-okhttp-1.9.0-sources.jar",
          "size": 6266,
          "sha512": "e32a4591d70abe03a48f1c6e80a71b2e40cbe45cfee466d14b984fcfe961e7e5e7c2e7d21c47e9c27dead6dec4c9881dd27329a50a72143006c54025fdd83af2",
          "sha256": "b37ab13b234ce2007c489d27568aeb3b1d7169ff50a09317e866ab7e75f7acca",
          "sha1": "6e13f003a88454fbce1d7586c5e9337db2942372",
          "md5": "7b8243210daddf35205041ce4e39c5f2"
        }
      ]
    }
  ]
}
